module.exports = {
  //constants between mobile and server
  JOIN_ROOM: 'join room',
  GO_TO_DRAWKWARD: 'go to drawkward',
  newUser: 'new user',
  newDrawing: 'new drawing',
  // newPhrase: 'new phrase',
  newGuess: 'new guess',
  receiveRandomPhrase: 'receive random phrase',
  sendStartGame: 'send start game',
  phraseOptions: 'phrase options',
  selectPhrase: 'select phrase',
  FORCE_SUBMIT_DRAWING: 'force submit drawing',
  youAreTheArtist: 'you are the artist',
  startCaption: 'start caption',
  scoreboard: 'scoreboard',
  nextDrawing: 'next drawing',
  gameOver: 'game over',

  //constants between server and webapp
  CREATE_NEW_ROOM: 'create new room',
  NEW_SOCKET_IN_ROOM: 'new socket in room',
  SEND_TO_DRAWKWARD: 'send to drawkward',
  receiveNewUser: 'receive new user',
  startGame: 'start game',
  receiveNewDrawing: 'receive new drawing',
  receiveNewGuess: 'receive new guess',
  sendRandomPhrase: 'send random phrase',
  TIME_IS_UP: 'time is up',
  sendToArtist: 'send to artist',
  sendStartCaption: 'send start caption',
  receivedAllCaptions: 'received all captions',
  receivedSelectedPhrase: 'receive selected phrase',
  lookAtScoreboard: 'look at scoreboard',
  seeNextDrawing: 'see next drawing',
  sendGameOver: 'send game over',

  //pictionary
    //between mobile and server
  NEW_TEAM: 'new team',
  CORRECT_GUESS: 'correct guess',
  SKIP: 'skip',
  RECEIVE_NEW_WORD: 'receive new word',
  NEW_LINE: 'new line',
  NEW_COORDINATES: 'new coordinates',
  START_TURN: 'start turn',
  END_TURN: 'end turn',
    //between server and webapp
  RECEIVE_NEW_TEAM: 'receive new team',
  PICK_STARTING_TEAM: 'pick starting team',
  START_NEW_LINE: 'start new line',
  RECEIVE_NEW_COORDINATES: 'receive new coordinates',
  CLEAR_CANVAS: 'clear canvas',
  ADD_POINTS: 'add points',
  FETCH_NEXT_WORD: 'next word',
  SEND_NEW_WORD: 'new word',
  TIMER_DONE: 'timer done',
};
