module.exports = {
  //constants between mobile and server
  newRoom: 'new room',
  newUser: 'new user',
  newDrawing: 'new drawing',
  // newPhrase: 'new phrase',
  newGuess: 'new guess',
  receiveRandomPhrase: 'receive random phrase',
  sendStartGame: 'send start game',
  phraseOptions: 'phrase options',
  selectPhrase: 'select phrase',
  youAreTheArtist: 'you are the artist',
  startCaption: 'start caption',
  scoreboard: 'scoreboard',
  nextDrawing: 'next drawing',
  gameOver: 'game over',

  //constants between server and webapp
  receiveNewUser: 'receive new user',
  startGame: 'start game',
  receiveNewDrawing: 'receive new drawing',
  receiveNewGuess: 'receive new guess',
  sendRandomPhrase: 'send random phrase',
  sendToArtist: 'send to artist',
  sendStartCaption: 'send start caption',
  receivedAllCaptions: 'received all captions',
  receivedSelectedPhrase: 'receive selected phrase',
  lookAtScoreboard: 'look at scoreboard',
  seeNextDrawing: 'see next drawing',
  sendGameOver: 'send game over',
};
